# Generated by Django 3.2.19 on 2023-06-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
