# Generated by Django 3.2.19 on 2023-06-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_productrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
